### ISSUE TITLE
[iOS New arch error] 'RNFastOpencvSpec.h' file not found 

### ISSUE THREAD

**Issue by leo6104** [lukaszkurantdev/react-native-fast-opencv#17]
<img width="825" alt="image" src="https://github.com/user-attachments/assets/b3fd767e-bc97-4193-898e-a9e7e4d55c54">

https://github.com/lukaszkurantdev/react-native-fast-opencv/blob/main/ios/FastOpencv.h#L19 

This line has an error. Is there any missing file on the repository?

**Comment by lukaszkurantdev** [comment]
Hi @leo6104, It's a file generated by codegen during Pods install process and it is inside Development Pods (and that's why it is not on the repository).

Simply install pods with the new architecture enabled in your project and the dependency will be available.

**Comment by leo6104** [comment]
@lukaszkurantdev Sorry for bothering you. I'm newbie at React Native new architecture process. 
Can i know which code in your project make `Pod` to create RNFastOpencvSpec.h automatically? 
I cannot find the occurrence/rules of `RNFastOpencvSpec` in the repository except `FastOpencv.h file` 

I setup `package.json` to 
```
    "pod-install": "cd ios && bundler install && RCT_NEW_ARCH_ENABLED=1 bundler exec pod install && cd ..",
```
and execute `npm run pod-install`. 
I think i did pod install with the new architecture enabled. 

To check whether i install new architecture or not, i checked Pod installed list and found RCT-Folly / React-Codegen which is included when new architecture mode on. (https://github.com/lukaszkurantdev/react-native-fast-opencv/blob/main/react-native-fast-opencv.podspec#L29)

**Comment by leo6104** [comment]
@lukaszkurantdev Thanks for kind explanation. I'm newbie on React Native new architecture and it was mis-configuraiton on my side. Sorry for bothering you 😅 Thanks.

**Comment by Alli018** [comment]
Hello @leo6104, did you solve the issue? Same with me, but I couldn't solve it. I tried using the most recent RN (0.76)... maybe if I use the old arch? Thanks.
