### ISSUE TITLE
Type Error on Base Import "Could not find a declaration file for module 'react-native-fast-opencv'."

### ISSUE THREAD

**Issue by GMoon777** [lukaszkurantdev/react-native-fast-opencv#18]
Hi, amazing work with this, just wanted to check as I can see many mentions of TypeScript in this repo. 

Are we expecting to not have a declaration file when importing OpenCV from react-native-fast-opencv

```
import { OpenCV } from "react-native-fast-opencv";
"Could not find a declaration file for module 'react-native-fast-opencv'."
```

Thanks.

**Comment by GMoon777** [comment]
I added `"types": "./lib/typescript/module/src/index.d.ts"` to the react-native-fast-opencv package.json and all the types are working now. 
Not sure why my project couldn't detect them without this addition.

**Comment by lukaszkurantdev** [comment]
@GMoon777 Probably it's related to your project TS configuration (some excludes?), the error does not occur on a clean project.

**Comment by GMoon777** [comment]
@lukaszkurantdev Thanks for getting back to me, it must be my typescript configuration then. I'll close this.
