### ISSUE TITLE
Feature Request: Add floodFill function to React Native Fast OpenCV

### ISSUE THREAD

**Issue by Junaid083** [lukaszkurantdev/react-native-fast-opencv#22]
## Description
I'm currently using the "React Native Fast OpenCV" package in a React Native application to integrate OpenCV functionality. The package provides most of the OpenCV functions I need, but it's missing the `floodFill` function, which is crucial for my project.

## Current Situation
The package currently provides the following OpenCV functions that I'm using:
- medianBlur
- Laplacian
- threshold
- mean

However, the `floodFill` function is not available, which limits the image processing capabilities in my React Native app.

## Feature Request
I would like to request the addition of the `floodFill` function to the "React Native Fast OpenCV" package. This function is an important part of the OpenCV library and would greatly enhance the package's functionality.

## Use Case
The `floodFill` function is essential for region filling and segmentation tasks in image processing. In my project, I need to use it for:
1. Isolating specific areas in images
2. Filling enclosed regions
3. Creating masks for further image processing

## Technical Details
In OpenCV, the `floodFill` function is typically used as follows:

```cpp
cv::floodFill(InputOutputArray image, InputOutputArray mask, Point seedPoint, Scalar newVal, Rect* rect=0, Scalar loDiff=Scalar(), Scalar upDiff=Scalar(), int flags=4)

**Comment by lukaszkurantdev** [comment]
Hi @Junaid083, I've added it in [v0.2.11](https://github.com/lukaszkurantdev/react-native-fast-opencv/releases/tag/v0.2.11).

The definition looks like this:
```js
invoke(
  name: 'floodFill',
  image: Mat,
  mask: Mat,
  seedPoint: Point,
  newVal: Scalar,
  rect: Rect,
  loDiff: Scalar,
  upDiff: Scalar,
  flags: FloodFillFlags | number
): { value: number };
```

More you can find in documentation [here](https://lukaszkurantdev.github.io/react-native-fast-opencv/availablefunctions#floodfill). If you have any problem with this, feel free to open next issue.

**Comment by Junaid083** [comment]
Hi @lukaszkurantdev , Thank you for adding the `floodFill` function in v0.2.11! This is a great addition to the package.

I wanted to mention that I've been using a custom C++ function to implement my scenario, as described in the [Customized section of the documentation](https://lukaszkurantdev.github.io/react-native-fast-opencv/customized). Here's a snippet of my implementation:

```
else if (propName == "customFunction")
	{
		return jsi::Function::createFromHostFunction(
				runtime, jsi::PropNameID::forAscii(runtime, "customFunction"), 1,
				[=](jsi::Runtime &runtime, const jsi::Value &thisValue, const jsi::Value *arguments, size_t count) -> jsi::String
				{
					if (count < 3)
					{
						// Return an error or handle insufficient arguments
						return jsi::String::createFromUtf8(runtime, "Insufficient arguments");
					}

					// Convert jsi::Value to std::string
					std::string base64String = arguments[0].asString(runtime).utf8(runtime);
					std::string x = arguments[1].asString(runtime).utf8(runtime);
					std::string y = arguments[2].asString(runtime).utf8(runtime);
					std::string hexColor = arguments[3].asString(runtime).utf8(runtime);

					cv::Mat image = ImageConverter::str2mat(base64String);

					double scale = 1.0 / 3.0;
					cv::resize(image, image, cv::Size(), scale, scale, cv::INTER_LINEAR);

					int rows = image.rows;
					int cols = image.cols;

					// Apply median blur
					cv::Mat blur;
					cv::medianBlur(image, blur, 5);

					// Apply Laplacian filter
					cv::Mat canny;
					cv::Laplacian(blur, canny, CV_8U, 3);

					// Convert to grayscale
					cv::cvtColor(canny, canny, cv::COLOR_BGR2GRAY);

					// Apply binary threshold
					cv::threshold(canny, canny, 75, 255, cv::THRESH_BINARY);

					// Create mask
					cv::Mat mask = cv::Mat::zeros(rows + 2, cols + 2, CV_8U);
					canny.copyTo(mask(cv::Rect(1, 1, cols, rows)));

					// Convert image to HLS color space
					cv::Mat hls;
					cv::cvtColor(image, hls, cv::COLOR_BGR2HLS);

					// Extract L channel
					cv::Mat l_channel;
					cv::extractChannel(hls, l_channel, 1);

					// Create a copy of the image
					cv::Mat dst = image.clone();

					// Create fill mask
					cv::Mat fill_mask = cv::Mat::zeros(rows + 2, cols + 2, CV_8U);

					// Convert string coordinates to integers
					int x_coord = std::stoi(x);
					int y_coord = std::stoi(y);

					// Perform flood fill
					cv::Scalar loDiff(3, 3, 3);
					cv::Scalar upDiff(3, 3, 3);
					cv::floodFill(dst, fill_mask, cv::Point(x_coord, y_coord), cv::Scalar(0, 0, 0),
												0, loDiff, upDiff, 4 | cv::FLOODFILL_MASK_ONLY);

					// Crop the fill mask to match the image size
					fill_mask = fill_mask(cv::Rect(1, 1, cols, rows));

					// Convert hex color to RGB
					cv::Scalar rgb_color = hex_to_rgb(hexColor);

					// Create a matrix filled with the RGB color
					cv::Mat color_mat(dst.size(), dst.type(), rgb_color);

					// Convert color matrix to HLS
					cv::Mat color_hls;
					cv::cvtColor(color_mat, color_hls, cv::COLOR_BGR2HLS);

					// Calculate mean of L channel where fill_mask is 1
					cv::Scalar l_mean = cv::mean(l_channel, fill_mask);

					// Extract L channel from color_hls
					cv::Mat color_l_channel;
					cv::extractChannel(color_hls, color_l_channel, 1);

					// Calculate mean of L channel in color_hls
					cv::Scalar color_l_mean = cv::mean(color_l_channel);

					// Calculate the difference
					double l_diff = color_l_mean[0] - l_mean[0];

					// Create a copy of the L channel
					cv::Mat new_l = l_channel.clone();

					// Adjust L channel values where fill_mask is 1
					for (int i = 0; i < new_l.rows; i++)
					{
						for (int j = 0; j < new_l.cols; j++)
						{
							if (fill_mask.at<uchar>(i, j) == 1)
							{
								int new_val = cv::saturate_cast<uchar>(new_l.at<uchar>(i, j) + l_diff);
								new_l.at<uchar>(i, j) = new_val;
							}
						}
					}

					// Create a copy of the HLS image
					cv::Mat new_hls = hls.clone();

					// Replace the L channel in new_hls
					std::vector<cv::Mat> hls_channels;
					cv::split(new_hls, hls_channels);
					hls_channels[1] = new_l;
					cv::merge(hls_channels, new_hls);

					// Adjust H and S channels where fill_mask is 1
					for (int i = 0; i < new_hls.rows; i++)
					{
						for (int j = 0; j < new_hls.cols; j++)
						{
							if (fill_mask.at<uchar>(i, j) == 1)
							{
								new_hls.at<cv::Vec3b>(i, j)[0] = color_hls.at<cv::Vec3b>(0, 0)[0];
								new_hls.at<cv::Vec3b>(i, j)[2] = color_hls.at<cv::Vec3b>(0, 0)[2];
							}
						}
					}

					// Convert back to BGR
					cv::Mat result;
					cv::cvtColor(new_hls, result, cv::COLOR_HLS2BGR);

					// Convert the resized image back to base64 string
					std::string finalResult = ImageConverter::mat2str(result);

					// std::string result = "Hello World " + param1 + " " + param2;

					// Return the result as a JS string
					return jsi::String::createFromUtf8(runtime, finalResult);
				});
	}
```

	
I'm looking forward to trying out the new `floodFill` function in the package. Thanks again for your work on this!

**Comment by Junaid083** [comment]
Hi @lukaszkurantdev ,I have an issue where, after deleting and reinstalling `node_modules`, I have to manually update a `.cpp` file inside the `node_modules` folder. Is there a way to handle this so I don't have to manually update the file every time?"

**Comment by lukaszkurantdev** [comment]
@Junaid083 Use [patch-package](https://www.npmjs.com/package/patch-package) on this library. Added patch file will be on your repository and changes will be added after each installation of libraries.

**Comment by Junaid083** [comment]
Hi @lukaszkurantdev ,

I’m working on a scenario where I aim to color a wall using your package. I’ve provided coordinates, a base64 image, and a hex code for the desired color.

It works reasonably well when the image quality is good, but in cases where the image is blurry or noisy (often due to mobile camera limitations), the results are not as accurate.

I’m attaching the updated `.cpp` file and a reference video. I would appreciate your help in optimizing the code to ensure precise results, focusing only on coloring the specific wall the user clicks on.

Looking forward to your input!


[react-native-fast-opencv.txt](https://github.com/user-attachments/files/17774048/react-native-fast-opencv.txt)


https://github.com/user-attachments/assets/a17aa461-f793-4626-886b-96fe2a17ac93

**Comment by lukaszkurantdev** [comment]
@Junaid083 I'm sorry, but this is just OpenCV specific question, not related to this port library. Please ask your questions in the OpenCV-specific repository.
