### ISSUE TITLE
On my android app is processing a period of time and suddenly stopped

### ISSUE THREAD

**Issue by kHanHnq4901** [lukaszkurantdev/react-native-fast-opencv#24]
<img width="1026" alt="Ảnh màn hình 2024-10-16 lúc 14 20 07" src="https://github.com/user-attachments/assets/53db8c58-0fcb-493a-b535-dd3171f7226b">

import { PaintStyle, Skia } from '@shopify/react-native-skia';
import { useEffect } from 'react';
import { StyleSheet, Text } from 'react-native';
import { ColorConversionCodes, ContourApproximationModes, DataTypes, ObjectType, OpenCV, Rect, RetrievalModes } from 'react-native-fast-opencv';
import {
  Camera,
  getCameraDevice,
  useCameraDevice,
  useCameraFormat,
  useCameraPermission,
  useSkiaFrameProcessor,
} from 'react-native-vision-camera';
import { useResizePlugin } from 'vision-camera-resize-plugin';
 
const paint = Skia.Paint();
paint.setStyle(PaintStyle.Fill);
paint.setColor(Skia.Color('lime'));
interface Point {
  x: number;
  y: number;
}

function distanceCalculate(p1: Point, p2: Point): number {
  return Math.sqrt((p2.x - p1.x) ** 2 + (p2.y - p1.y) ** 2);
}
export default function VisionCameraExample() {
  const devices = Camera.getAvailableCameraDevices()
  const device = getCameraDevice(devices, 'back', {
    physicalDevices: [
      'wide-angle-camera',
    ]
  })
  const format = useCameraFormat(device, [

    { videoResolution: { width: 1280, height: 720 } },
    { fps: 7 }
  ])

  const { hasPermission, requestPermission } = useCameraPermission();
 
  const { resize } = useResizePlugin();
 
  useEffect(() => {
    requestPermission();
  }, [requestPermission]);
 
  const frameProcessor = useSkiaFrameProcessor((frame) => {
    'worklet';
  
    const scaledHeight = frame.height / 6;
    const scaledWidth = frame.width / 6;
  
    // Resize the frame
    const resized = resize(frame, {
      scale: {
        width: scaledWidth,
        height: scaledHeight,
      },
      pixelFormat: 'bgr',
      dataType: 'uint8',
    });
  
    // Extract the pixel data from the resized frame
    const pixelData = resized; // Assuming 'resized' has the pixel data in the 'data' property
  
    // Convert frame buffer to OpenCV Mat object (passing 4 arguments: rows, cols, channels, and input)
    const src = OpenCV.frameBufferToMat(scaledHeight, scaledWidth, 3, pixelData);
    const dst = OpenCV.createObject(ObjectType.Mat, 0, 0, DataTypes.CV_8U);
  
    const lowerBound = OpenCV.createObject(ObjectType.Scalar, 150, 50, 50);
    const upperBound = OpenCV.createObject(ObjectType.Scalar, 180, 255, 255);
    OpenCV.invoke('cvtColor', src, dst, ColorConversionCodes.COLOR_BGR2HSV);
    OpenCV.invoke('inRange', dst, lowerBound, upperBound, dst);
  
    
    const contours = OpenCV.createObject(ObjectType.MatVector);
    OpenCV.invoke(
      'findContours',
      dst,
      contours,
      RetrievalModes.RETR_EXTERNAL,
      ContourApproximationModes.CHAIN_APPROX_SIMPLE
    );
  
    const contoursMats = OpenCV.toJSValue(contours);
    const rectangles: Rect[] = [];
  
    for (let i = 0; i < contoursMats.array.length; i++) {
      if (contoursMats.array.length == 3 ){
        console.log (contoursMats.array.length)
      }

    
      const contour = OpenCV.copyObjectFromVector(contours, i);
      const { value: area } = OpenCV.invoke('contourArea', contour, false);
  
      if (area > 10) {
        const rect = OpenCV.invoke('boundingRect', contour);
        rectangles.push(rect);
      }
    }
  
    frame.render();
  
    for (const rect of rectangles) {
      const rectangle = OpenCV.toJSValue(rect);
  
      frame.drawRect(
        {
          height: rectangle.height * 6,
          width: rectangle.width * 6,
          x: rectangle.x * 6,
          y: rectangle.y * 6,
        },
        paint
      );
    }
  
    OpenCV.clearBuffers(); // Clean OpenCV resources
  }, []);
  
 
  if (!hasPermission) {
    return <Text>No permission</Text>;
  }
 
  if (device == null) {
    return <Text>No device</Text>;
  }
 
  return (
    <Camera
      style={StyleSheet.absoluteFill}
      device={device}
      isActive={true}
      frameProcessor={frameProcessor}
      enableFpsGraph={true}
      format={format}

    />
  );
}

**Comment by kHanHnq4901** [comment]
@lukaszkurantdev

**Comment by lukaszkurantdev** [comment]
Hi, 
1. Please, next time you report an issue, make it clearer.
2. I saw that you added a similar issue on the vision camera repository, adding different code to the same screenshot, so I conclude that this is not a problem with this library (as you can see from the screenshot).

Closing.
