### ISSUE TITLE
'RNFastOpencvSpec.h' file not found

### ISSUE THREAD

**Issue by AbdullahJaspal** [lukaszkurantdev/react-native-fast-opencv#32]
I encountered a build error while integrating react-native-fast-opencv into my React Native project. The error appears when attempting to build the iOS application in Xcode.

Here is the exact error message from Xcode:

```
In file included from ProjectRootDirectory/node_modules/react-native-fast-opencv/ios/FastOpencv.mm:1:
'RNFastOpencvSpec.h' file not found
```

**Steps to Reproduce**

- Install the library: yarn add react-native-fast-opencv.
- Run cd ios && pod install.
- Open the project in Xcode (ios/YourApp.xcworkspace).
- Attempt to build the project.

**What I Tried**

Here are the steps I attempted to resolve the issue:

1. Deleted the Derived Data folder and cleaned the build folder.
2. Rebuilt the project in Xcode.
3. Deleted the node_modules folder, Pods folder, and Podfile.lock file.
4. Reinstalled dependencies by running:
5. yarn install
6. cd ios && pod install
7. Downgraded the library to version ^0.2.13.
8. In my ios folder i have also tried 
`RCT_NEW_ARCH_ENABLED=1 bundle exec pod install`

Unfortunately, none of these steps resolved the issue, and the build error persists.

**Additional Information**

Library Version: "react-native-fast-opencv": "^0.3.0",
React Native Version: "react-native": "0.76.1",
Node Version: v18.18.0
Yarn Version: 3.6.4
Xcode Version: Version 16.0 
macOS Version: 15.0.1

**Comment by lukaszkurantdev** [comment]
@AbdullahJaspal Thanks for detailed issue description. 

It looks like there is a problem with codegen with new RN version. I've added new update `v0.3.1` with fix. Please try again with this new version.

**Comment by AbdullahJaspal** [comment]
I’ve tried the newer version (v0.3.1) and the build was successful. Thanks for the fix!
