### ISSUE TITLE
how to create empty png mat?

### ISSUE THREAD

**Issue by i7soft** [lukaszkurantdev/react-native-fast-opencv#40]
i want to create a empty png mat, and then drawContours on it. My code like this:

`OpenCV.createObject(ObjectType.Mat, 256, 256, DataTypes.CV_8UC4)` 

but the mat is fill with black color, i want all the pixels are transparency

**Comment by i7soft** [comment]
open file:
node_modules/react-native-fast-opencv/cpp/ConvertImage.cpp

at line  145:

cv::imencode(".jpeg", m, buf); 

change to 

cv::imencode(".png", m, buf);

**Comment by lukaszkurantdev** [comment]
> open file: node_modules/react-native-fast-opencv/cpp/ConvertImage.cpp
> 
> at line 145:
> 
> cv::imencode(".jpeg", m, buf);
> 
> change to
> 
> cv::imencode(".png", m, buf);

@i7soft Is it fixed your problem?

**Comment by i7soft** [comment]
> > open file: node_modules/react-native-fast-opencv/cpp/ConvertImage.cpp
> > at line 145:
> > cv::imencode(".jpeg", m, buf);
> > change to
> > cv::imencode(".png", m, buf);
> 
> @i7soft Is it fixed your problem?

yes, and I suggest add a parameter to OpenCV.toJSValue, support output png

**Comment by lukaszkurantdev** [comment]
@i7soft Right, good point. I'll add it in the next release.

**Comment by lukaszkurantdev** [comment]
I've added it in `0.3.4`. Now, `toJSValue` function has a second parameter and possibility to return base64 in jpeg or png.

```js
toJSValue(
    mat: Mat,
    outImageFormat?: 'jpeg' | 'png'
)
```

**Comment by i7soft** [comment]
> I've added it in `0.3.4`. Now, `toJSValue` function has a second parameter and possibility to return base64 in jpeg or png.
> 
> ```js
> toJSValue(
>     mat: Mat,
>     outImageFormat?: 'jpeg' | 'png'
> )
> ```

Thank you for your work. I have updated it
