### ISSUE TITLE
optical form reading

### ISSUE THREAD

**Issue by ersyhsyn** [lukaszkurantdev/react-native-fast-opencv#41]
Hello;  What I want to ask is that I want to do optical form reading through the camera.  Whether this is possible with the currently available functions.  Do you think we can do it using this library? There was document capture on your medium page.  I'm trying to start from there, but I would appreciate it if you could guide me.

**Comment by i7soft** [comment]
use react-native-vision-camere

[https://lukaszkurantdev.github.io/react-native-fast-opencv/installation/visioncamera](url)

**Comment by lukaszkurantdev** [comment]
@ersyhsyn 
This library is a port for the OpenCV library. Everything that can be done in OpenCV can be done in this port (either on the JavaScript side, or if some API is missing then on the C++ side).

OpenCV helps with image processing, so if the form is quite distinctive, it would probably be possible to extract selected fields. However, for OCR you will need another library such as Tesseract or MLKit.

So the flow could look like this:
Photo -> OpenCV crop and image processing -> OCR -> further processing.

**Comment by ersyhsyn** [comment]
Thank you for your information. After taking care of the image processing part, I need to read characters with Tesseract or MLKit.  I couldn't find any sample projects made with react native.  There are Android etc. but they are also quite old. If I am successful, I will write here.
