### ISSUE TITLE
Package not linked

### ISSUE THREAD

**Issue by fromtheeast710** [lukaszkurantdev/react-native-fast-opencv#42]
I'm using the package with an Expo + React Native template. I tried copy paste the (real-time detection example)[https://github.com/lukaszkurantdev/react-native-fast-opencv/blob/main/example/src/examples/CameraRealtimeDetection.tsx] but when viewing the web page, it shows the following error:
```
The package 'react-native-fast-opencv' doesn't seem to be linked. Make sure: 

- You rebuilt the app after installing the package
- You are not using Expo Go
```

**Comment by lukaszkurantdev** [comment]
> but when viewing the web page

@fromtheeast710 This lib is only for iOS / Android and does not work for web. Generally Expo is not supported, but it should work with bare workflow or with EAS.

**Comment by aeltersxops** [comment]
@lukaszkurantdev Are there any plans to support Expo? I have created an expo module that is only available for android and iOS but I am failing to make this work within it.
