### ISSUE TITLE
Feedback for “Real-time detection”

### ISSUE THREAD

**Issue by skudirka-tw** [lukaszkurantdev/react-native-fast-opencv#48]
How do I get the Laplacian value of an image? Can you provide an example?

**Comment by lukaszkurantdev** [comment]
Hi @skudirka-tw . It is in documentation: https://lukaszkurantdev.github.io/react-native-fast-opencv/availablefunctions#laplacian

For example:
```js
OpenCV.invoke( 'Laplacian', src, dst, DataTypes.CV_64F, 1, 1, 0, BorderTypes.BORDER_DEFAULT);
```

Please remember that this library is **a port** to OpenCV. If you have any questions about the use of the API in React Native then go ahead and ask, however if they relate to OpenCV itself please ask them in the appropriate place (StackOverflow or OpenCV GitHub).
