### ISSUE TITLE
Can I use this library for face recognition?

### ISSUE THREAD

**Issue by shuo-hiwintech** [lukaszkurantdev/react-native-fast-opencv#5]
Thanks to the author for developing a great plugin.

I'm planning to make a face recognition feature with react-native-vision-camera's realtime frame processing.

After looking through the documentation to find this plugin developed by the author, I looked through the react-native-fast-opencv documentation but did not find an api for face recognition.

So how would I import a trained file like haarcascade_frontalface_default for face recognition via react-native-fast-opencv?

Thanks!

**Comment by lukaszkurantdev** [comment]
Hi @shuo-hiwintech, unfortunately face detection is currently not supported by the library. In such cases, it is possible to write your own code in C++ using such functionality.

Instructions are available here: https://lukaszkurantdev.github.io/react-native-fast-opencv/customized
